### ISSUE TITLE
[ISSUE] breaks on linux after inputing unlock codes and username

### ISSUE THREAD

**Issue by Mysticpasta1** [SerrpentDagger/graphing-calculator-sd#4]
[TIME: 1579ms] -- jakarta/xml/bind/DatatypeConverter
[TIME: 1579ms] -- java.lang.NoClassDefFoundError: jakarta/xml/bind/DatatypeConverter
at J.A.A(Unknown Source)
at J.A.A(Unknown Source)
at J.C.B(Unknown Source)
at J.C.A(Unknown Source)
at F.A.f(Unknown Source)
at F.A.Z(Unknown Source)
at main.MainLoop.C(Unknown Source)
at main.MainLoop.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.DatatypeConverter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
... 8 more

[TIME: 1579ms] -- You can check for help about this crash on the GitHub isssue tracker, at <https://github.com/SerrpentDagger/graphing-calculator-sd/issues>. If it has not been adressed, please post a new issue, so that I can fix it.
[TIME: 1579ms] -- Shutting down
[TIME: 1580ms] -- Saving settings
Exception in thread "main" java.lang.IllegalStateException: Batch is already started.
at files.WorkingFolder.startBatch(WorkingFolder.java:295)
at F.A.C(Unknown Source)
at main.MainLoop.B(Unknown Source)
at main.MainLoop.main(Unknown Source)

**Comment by SerrpentDagger** [comment]
This was caused by a difference in Java version between my IDE and the version expected to run this program. I've now sorted that out and updated the latest release with the fix, so this shouldn't be an issue anymore. Thanks for the crash report.
